"use client";

import Link from "next/link";

import {
  ArrowLeft,
  Gift,
  Coins,
  Trophy,
  Star,
  Bot,
  Users,
  Target,
  Search,
  ArrowUpRight,
} from "lucide-react";

export default function RewardsPage() {
  return (
    <main className="min-h-screen bg-[#050B18] text-white">

      <div className="max-w-md mx-auto px-5 py-6 pb-28">

        {/* Header */}

        <div className="flex items-center justify-between mb-8">

          <Link href="/dashboard">

            <button className="w-12 h-12 rounded-2xl border border-slate-800 bg-[#101A2C] flex items-center justify-center">

              <ArrowLeft size={22} />

            </button>

          </Link>

          <div className="text-center">

            <h1 className="text-2xl font-bold">
              Rewards
            </h1>

            <p className="mt-1 text-sm text-slate-400">
              Earn rewards and bonuses
            </p>

          </div>

          <div className="w-12 h-12 rounded-2xl border border-slate-800 bg-[#101A2C] flex items-center justify-center">

            <Gift
              size={22}
              className="text-cyan-400"
            />

          </div>

        </div>

        {/* Rewards Card */}

        <div className="rounded-3xl bg-gradient-to-br from-cyan-500 to-blue-700 p-6">

          <div className="flex items-center justify-between">

            <div>

              <h2 className="text-2xl font-bold">
                Rewards Balance
              </h2>

              <p className="mt-2 text-cyan-100">
                Your total available rewards.
              </p>

            </div>

            <Gift
              size={46}
              className="text-white"
            />

          </div>

          <div className="mt-6 rounded-2xl bg-white/10 p-4">

            <p className="text-sm text-cyan-100">
              Total Rewards
            </p>

            <p className="mt-2 text-3xl font-bold">
              0 TON
            </p>

          </div>

        </div>

        {/* Search */}

        <div className="mt-8">

          <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-[#101A2C] px-4 py-4">

            <Search
              size={22}
              className="text-slate-400"
            />

            <input
              type="text"
              placeholder="Search rewards..."
              className="w-full bg-transparent outline-none placeholder:text-slate-500"
            />

          </div>

        </div>

        {/* Rewards Overview */}
        <div className="mt-8 space-y-4">

          {/* Referral Rewards */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-center justify-between">

              <div className="flex items-center gap-4">

                <div className="w-14 h-14 rounded-2xl bg-cyan-500/10 flex items-center justify-center">

                  <Users
                    size={28}
                    className="text-cyan-400"
                  />

                </div>

                <div>

                  <h3 className="font-bold text-lg">
                    Referral Rewards
                  </h3>

                  <p className="text-sm text-slate-400">
                    Earn rewards by inviting friends.
                  </p>

                </div>

              </div>

              <p className="font-bold">
                0 TON
              </p>

            </div>

          </div>

          {/* AI Trading Rewards */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-center justify-between">

              <div className="flex items-center gap-4">

                <div className="w-14 h-14 rounded-2xl bg-purple-500/10 flex items-center justify-center">

                  <Bot
                    size={28}
                    className="text-purple-400"
                  />

                </div>

                <div>

                  <h3 className="font-bold text-lg">
                    AI Trading Rewards
                  </h3>

                  <p className="text-sm text-slate-400">
                    Rewards generated by AI Trading.
                  </p>

                </div>

              </div>

              <p className="font-bold">
                0 TON
              </p>

            </div>

          </div>

          {/* Bonus Rewards */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-center justify-between">

              <div className="flex items-center gap-4">

                <div className="w-14 h-14 rounded-2xl bg-yellow-500/10 flex items-center justify-center">

                  <Coins
                    size={28}
                    className="text-yellow-400"
                  />

                </div>

                <div>

                  <h3 className="font-bold text-lg">
                    Bonus Rewards
                  </h3>

                  <p className="text-sm text-slate-400">
                    Promotional and loyalty bonuses.
                  </p>

                </div>

              </div>

              <p className="font-bold">
                0 TON
              </p>

            </div>

          </div>

        </div>

        {/* Reward Levels */}
        <div className="mt-8">

          <h2 className="text-xl font-bold mb-4">
            Reward Levels
          </h2>

          <div className="space-y-4">

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center justify-between">

                <div className="flex items-center gap-4">

                  <Trophy
                    size={28}
                    className="text-amber-500"
                  />

                  <div>

                    <h3 className="font-bold">
                      Bronze
                    </h3>

                    <p className="text-sm text-slate-400">
                      Entry reward level
                    </p>

                  </div>

                </div>

                <span className="font-bold text-amber-500">
                  Active
                </span>

              </div>

            </div>

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center justify-between">

                <div className="flex items-center gap-4">

                  <Star
                    size={28}
                    className="text-slate-300"
                  />

                  <div>

                    <h3 className="font-bold">
                      Silver
                    </h3>

                    <p className="text-sm text-slate-400">
                      Unlock with more rewards
                    </p>

                  </div>

                </div>

                <span className="text-slate-500">
                  Locked
                </span>

              </div>

            </div>

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center justify-between">

                <div className="flex items-center gap-4">

                  <Trophy
                    size={28}
                    className="text-yellow-400"
                  />

                  <div>

                    <h3 className="font-bold">
                      Gold
                    </h3>

                    <p className="text-sm text-slate-400">
                      Premium reward benefits
                    </p>

                  </div>

                </div>

                <span className="text-slate-500">
                  Locked
                </span>

              </div>

            </div>

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center justify-between">

                <div className="flex items-center gap-4">

                  <Trophy
                    size={28}
                    className="text-cyan-400"
                  />

                  <div>

                    <h3 className="font-bold">
                      Platinum
                    </h3>

                    <p className="text-sm text-slate-400">
                      Highest reward tier
                    </p>

                  </div>

                </div>

                <span className="text-slate-500">
                  Locked
                </span>

              </div>

            </div>

          </div>

        </div>

        {/* Missions */}
         <div className="mt-8">

          <h2 className="text-xl font-bold mb-4">
            Missions
          </h2>

          <div className="space-y-4">

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center gap-4">

                <Target
                  size={28}
                  className="text-cyan-400"
                />

                <div>

                  <h3 className="font-bold">
                    Complete KYC
                  </h3>

                  <p className="text-sm text-slate-400">
                    Reward: +10 TON
                  </p>

                </div>

              </div>

            </div>

            <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

              <div className="flex items-center gap-4">

                <Users
                  size={28}
                  className="text-green-400"
                />

                <div>

                  <h3 className="font-bold">
                    Invite 5 Friends
                  </h3>

                  <p className="text-sm text-slate-400">
                    Reward: +25 TON
                  </p>

                </div>

              </div>

            </div>

          </div>

        </div>

        {/* Actions */}

        <div className="mt-8 grid grid-cols-2 gap-4">

          <button className="rounded-3xl bg-cyan-500 py-5 font-bold text-black flex items-center justify-center gap-2">

            <Gift size={22} />

            Claim Rewards

          </button>

          <button className="rounded-3xl border border-slate-800 bg-[#101A2C] py-5 font-bold flex items-center justify-center gap-2">

            <ArrowUpRight size={22} />

            Transfer Rewards

          </button>

        </div>

        {/* Footer */}

        <div className="mt-10 text-center">

          <p className="text-sm text-slate-500">
            AI TONKEEPER Rewards Center
          </p>

          <p className="mt-2 font-semibold text-cyan-400">
            ai-tonkeeper.xyz
          </p>

          <p className="mt-6 text-xs text-slate-600">
            © 2026 AI TONKEEPER. All rights reserved.
          </p>

        </div>

      </div>

    </main>

  );
}