"use client";

import Link from "next/link";

import {
  ArrowLeft,
  Brain,
  TrendingUp,
  TrendingDown,
  Bell,
  Search,
} from "lucide-react";

export default function AISignalsPage() {
  return (
    <main className="min-h-screen bg-[#050B18] text-white">

      <div className="mx-auto w-full max-w-md px-5 py-6 pb-28">

        {/* Header */}

        <div className="mb-8 flex items-center justify-between">

          <Link href="/dashboard">

            <button className="flex h-12 w-12 items-center justify-center rounded-2xl border border-slate-800 bg-[#101A2C]">

              <ArrowLeft size={22} />

            </button>

          </Link>

          <div className="flex-1 px-3 text-center">

            <h1 className="text-2xl font-bold">
              AI Signals
            </h1>

            <p className="mt-1 text-sm text-slate-400">
              Smart crypto trading signals
            </p>

          </div>

          <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-slate-800 bg-[#101A2C]">

            <Bell
              size={22}
              className="text-cyan-400"
            />

          </div>

        </div>

        {/* Hero */}

        <div className="rounded-3xl bg-gradient-to-br from-cyan-500 to-blue-700 p-6">

          <div className="flex items-center justify-between gap-4">

            <div className="min-w-0 flex-1">

              <h2 className="text-2xl font-bold">
                AI Trading Signals
              </h2>

              <p className="mt-2 text-sm text-cyan-100">
                Receive intelligent buy and sell opportunities generated by AI.
              </p>

            </div>

            <Brain
              size={46}
              className="shrink-0 text-white"
            />

          </div>

          <div className="mt-6 rounded-2xl bg-white/10 p-5">

            <p className="text-sm text-cyan-100">
              Active Signals
            </p>

            <p className="mt-2 text-4xl font-bold">
              0
            </p>

          </div>

        </div>

        {/* Search */}

        <div className="mt-8">

          <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-[#101A2C] px-4 py-4">

            <Search
              size={22}
              className="shrink-0 text-slate-400"
            />

            <input
              type="text"
              placeholder="Search signals..."
              className="w-full bg-transparent text-white outline-none placeholder:text-slate-500"
            />

          </div>

        </div>

        {/* Signals List */}
        <div className="mt-8 space-y-4">

          {/* BUY Signal */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-start justify-between gap-4">

              <div className="flex min-w-0 flex-1 items-start gap-4">

                <TrendingUp
                  size={30}
                  className="shrink-0 text-green-400"
                />

                <div className="min-w-0 flex-1">

                  <h3 className="text-lg font-bold">
                    BUY Signal
                  </h3>

                  <p className="mt-2 text-sm text-slate-400">
                    AI has detected a potential buying opportunity.
                  </p>

                </div>

              </div>

              <span className="shrink-0 rounded-xl bg-green-500/20 px-3 py-1 text-sm font-bold text-green-400">

                BUY

              </span>

            </div>

          </div>

          {/* SELL Signal */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-start justify-between gap-4">

              <div className="flex min-w-0 flex-1 items-start gap-4">

                <TrendingDown
                  size={30}
                  className="shrink-0 text-red-400"
                />

                <div className="min-w-0 flex-1">

                  <h3 className="text-lg font-bold">
                    SELL Signal
                  </h3>

                  <p className="mt-2 text-sm text-slate-400">
                    AI recommends reducing exposure based on market conditions.
                  </p>

                </div>

              </div>

              <span className="shrink-0 rounded-xl bg-red-500/20 px-3 py-1 text-sm font-bold text-red-400">

                SELL

              </span>

            </div>

          </div>

          {/* Market Overview */}

          <div className="rounded-3xl border border-slate-800 bg-[#101A2C] p-5">

            <div className="flex items-start gap-4">

              <Brain
                size={30}
                className="shrink-0 text-cyan-400"
              />

              <div className="min-w-0 flex-1">

                <h3 className="text-lg font-bold">
                  Market Overview
                </h3>

                <p className="mt-2 text-sm text-slate-400">
                  AI continuously analyzes market sentiment and identifies potential trading opportunities.
                </p>

              </div>

            </div>

          </div>

        </div>

        {/* Signal Performance */}
        <div className="mt-8 rounded-3xl border border-slate-800 bg-[#101A2C] p-6">

          <h2 className="text-xl font-bold">
            Signal Performance
          </h2>

          <div className="mt-6 space-y-5">

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Accuracy
              </span>

              <span className="font-bold text-green-400">
                0%
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Total Signals
              </span>

              <span className="font-bold">
                0
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Winning Signals
              </span>

              <span className="font-bold text-cyan-400">
                0
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Average Return
              </span>

              <span className="font-bold text-green-400">
                +0.00%
              </span>

            </div>

          </div>

        </div>

        {/* AI Confidence */}

        <div className="mt-8 rounded-3xl bg-gradient-to-br from-cyan-500 to-blue-700 p-6">

          <div className="flex items-center justify-between gap-4">

            <div className="min-w-0 flex-1">

              <h2 className="text-xl font-bold">
                AI Confidence
              </h2>

              <p className="mt-2 text-sm text-cyan-100">
                Confidence level calculated from market data and AI analysis.
              </p>

            </div>

            <Brain
              size={40}
              className="shrink-0 text-white"
            />

          </div>

          <div className="mt-6">

            <div className="h-3 w-full overflow-hidden rounded-full bg-white/20">

              <div className="h-full w-0 rounded-full bg-white"></div>

            </div>

            <div className="mt-3 flex items-center justify-between text-sm">

              <span>
                Confidence
              </span>

              <span className="font-bold">
                0%
              </span>

            </div>

          </div>

        </div>

        {/* Signal Statistics */}
        <div className="mt-8 rounded-3xl border border-slate-800 bg-[#101A2C] p-6">

          <h2 className="text-xl font-bold">
            Signal Statistics
          </h2>

          <div className="mt-6 space-y-4">

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Buy Signals
              </span>

              <span className="font-bold text-green-400">
                0
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Sell Signals
              </span>

              <span className="font-bold text-red-400">
                0
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Active Alerts
              </span>

              <span className="font-bold text-cyan-400">
                0
              </span>

            </div>

            <div className="flex items-center justify-between">

              <span className="text-slate-400">
                Last Update
              </span>

              <span className="font-bold">
                Just now
              </span>

            </div>

          </div>

        </div>

        {/* Footer */}

        <footer className="mt-10 border-t border-slate-800 pt-6 text-center">

          <p className="text-sm text-slate-500">
            AI TONKEEPER AI Signals
          </p>

          <p className="mt-2 font-semibold text-cyan-400">
            ai-tonkeeper.xyz
          </p>

          <p className="mt-4 text-xs text-slate-600">
            © 2026 AI TONKEEPER. All rights reserved.
          </p>

        </footer>

      </div>

    </main>

  );
}